[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "autoTSmin"
version = "0.1.0"
description = "Automatic transition-state and final-state searching based on LASP"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["numpy","pandas"]
authors = [
    {name = "Sicong Ma"}
]
[tool.setuptools.packages.find]
where = ["src"]
